function Privacy(){
    return(
        <div className="Privacy">
            <h1>PRIVACY NOTICE</h1>
            <ul>
                <li className="PrivacyTitle">CHANGES</li>
                <li>
                Tasha may make changes to the content and Services offered on the Sites or via the Mobile Applications at any time. Tasha can change, update, or add or remove provisions of these Terms, at any time by posting the updated Terms on the applicable Site(s). By using any Site or Mobile Application after Tasha has updated the Terms, you are agreeing to all the updated Terms; if you do not agree with any of the updated Terms, you must stop using the Sites and Mobile Applications.
                </li>
                <li className="PrivacyTitle">GENERAL USE</li>
                <li>
                By using a Site or Mobile Application, you represent, acknowledge and agree that you are at least 18 years of age, or if you are under 18 years of age but are at least 13 years old (a “Minor”), that you are using the Site and/or Mobile Application with the consent of your parent or legal guardian and that you have received your parent’s or legal guardian’s permission to agree to these Terms. If you are a parent or legal guardian of a Minor, you hereby agree to bind the Minor to these Terms and to fully indemnify and hold harmless Tasha if the Minor breaches any of these Terms. Our Sites and Mobile Applications are not targeted toward, nor intended for use by, anyone under the age of 13. If you are not at least 13 years old, you may not use our Sites or Mobile Applications at any time or in any manner or submit any information to Tasha, the Sites or the Mobile Applications.
                </li>
                <li>
                Tasha provides content through the Sites and Mobile Applications that is copyrighted and/or trademarked work of Tasha, Tasha’s third-party licensors and suppliers, or other users of the Sites and/or Mobile Applications (collectively, the “Materials”). Materials may include logos, graphics, video, images, software and other content. Subject to the terms and conditions of these Terms, and your compliance with these Terms, Tasha hereby grants you a limited, personal, non-exclusive and non-transferable license to use and to display the Materials and to use the Sites solely for your personal use. Except for the foregoing license (and the license set forth in the section below entitled Mobile Applications), you have no other rights in the Sites or any Materials and you may not modify, edit, copy, reproduce, create derivative works of, reverse engineer, alter, enhance or in any way exploit any Site, Mobile Application or Materials in any manner.

If you breach any of these Terms, the above license will terminate automatically and you must immediately destroy any downloaded or printed Materials.
                </li>
                <li className="PrivacyTitle">USING THE SITE AND THE SERVICES</li>
                <li>You need not register with Tasha to simply visit and view the Sites and use many of the Services available on the Sites or Mobile Applications. However, Tasha may from time to time require you to register for an account with Tasha in order to access certain password-restricted areas of a Site and to use certain Services and Materials offered on and through a Site or Mobile Application.</li>
                <li>If account registration is offered and you desire to register for an account with Tasha, you must submit information via the Mobile Application or through the account registration page on the Site (as applicable), which may include your e-mail address, name and mailing address. You may also have the ability to provide additional optional information about yourself, which is not required to register for the account, but may be helpful to Tasha in providing you with a more customized experience when using the Site, the Mobile Application or the Services they provide. Once you have submitted your account registration information, Tasha shall have the right to approve or reject the requested account, in Tasha’s discretion. If your account is approved, you will be permitted to log in to the applicable Site(s) or Service(s) using the password you select.</li>
                <li>You may also be provided with the ability to register for an account on the Site or Mobile Application using your existing account and log-in credentials through certain Third-Party Sites (as defined below) such as Facebook.</li>
                <li>You are responsible for maintaining the confidentiality of your Tasha password and any Third-Party Site password used to access our Sites, Mobile Applications and/or Services (collectively, “Passwords”), and you are responsible for all activities that occur using your Passwords. You agree not to share your Passwords, let others access or use your Passwords, or do anything else that might jeopardize the security of your Passwords. You agree to notify Tasha if any of your Passwords are lost or stolen, if you are aware of any unauthorized use of your Passwords or if you know of any other breach of security in relation to any Site or Mobile Application.</li>
                <li>All the information that you provide when registering for an account and otherwise through the Sites or Mobile Applications must be accurate, complete and up to date. You may change, correct or remove any information from your account by logging into your account directly and making the desired changes.</li>
                <li className="PrivacyTitle">DISCLAIMER OF WARRANTIESS</li>
                <li>
                Your use of the Sites, Mobile Applications and Services is at your own risk. The Materials have not been verified or authenticated in whole or in part by Tasha, and they may include inaccuracies or typographical or other errors. Tasha does not warrant the accuracy or timeliness of the Materials contained on the Sites and/or Mobile Applications. Tasha has no liability for any errors or omissions in the Materials, whether provided by Tasha, our licensors or suppliers or other users.
                </li>
                <li>
                Tasha, FOR ITSELF AND ITS LICENSORS, MAKES NO EXPRESS, IMPLIED OR STATUTORY REPRESENTATIONS, WARRANTIES, OR GUARANTEES IN CONNECTION WITH THE SITES, THE MOBILE APPLICATIONS, THE SERVICES, OR ANY MATERIALS, OR RELATING TO THE QUALITY, SUITABILITY, TRUTH, ACCURACY OR COMPLETENESS OF ANY INFORMATION CONTAINED OR PRESENTED ON THE SITES OR MOBILE APPLICATIONS. UNLESS OTHERWISE EXPLICITLY STATED, TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, THE SITES, THE MOBILE APPLICATIONS, THE SERVICES, THE MATERIALS, AND ANY INFORMATION CONTAINED OR PRESENTED ON THE SITES AND/OR MOBILE APPLICATIONS IS PROVIDED TO YOU ON AN “AS IS,” “AS AVAILABLE” AND “WHERE-IS” BASIS WITH NO WARRANTY OR IMPLIED WARRANTY OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, OR NON-INFRINGEMENT OF THIRD-PARTY RIGHTS. Tasha DOES NOT PROVIDE ANY WARRANTIES AGAINST VIRUSES, SPYWARE OR MALWARE THAT MAY BE INSTALLED ON YOUR COMPUTER.
                </li>

                <li className="PrivacyTitle">LIMITATION OF LIABILITY</li>
                <li>
                Tasha SHALL NOT BE LIABLE TO YOU FOR ANY DAMAGES RESULTING FROM YOUR USE OF THE SITES, MOBILE APPLICATIONS OR ANY SERVICES, OR FROM YOUR DISPLAYING, COPYING, OR DOWNLOADING ANY MATERIALS TO OR FROM THE SITES. IN NO EVENT SHALL Tasha BE LIABLE TO YOU FOR ANY INDIRECT, EXTRAORDINARY, EXEMPLARY, PUNITIVE, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES (INCLUDING LOSS OF DATA, REVENUE, PROFITS, USE OR OTHER ECONOMIC ADVANTAGE) HOWEVER ARISING, EVEN IF Tasha KNOWS THERE IS A POSSIBILITY OF SUCH DAMAGE.
                </li>
                <li>
                <li className="PrivacyTitle">  LOCAL LAWS; EXPORT CONTROL</li>
              <li>Tasha controls and operates the Sites and/or Mobile Applications from its offices in the United States of America, and the Services, Materials and Mobile Applications may not be appropriate or available for use in other locations. If you use a Site, Mobile Application and/or Services outside the United States of America, you are solely responsible for following applicable local laws.</li>
              <li className="PrivacyTitle">  FEEDBACK</li>
              <li>
                If you send or transmit any communications, comments, questions, suggestions, or related materials to Tasha, whether by letter, email, telephone, or otherwise (collectively, “Feedback”), suggesting or recommending changes to a Site, a Mobile Application, any Services, or any Materials, including, without limitation, new features or functionality relating thereto, all such Feedback is, and will be treated as non-confidential and non-proprietary. You hereby assign all right, title, and interest in, and Tasha is free to use, without any attribution or compensation to you, any ideas, know-how, concepts, techniques, or other intellectual property and proprietary rights contained in the Feedback, whether or not patentable, for any purpose whatsoever, including but not limited to, developing, manufacturing, having manufactured, licensing, marketing, and selling, directly or indirectly, products and services using such Feedback. You understand and agree that Tasha is not obligated to use, display, reproduce, or distribute any such ideas, know-how, concepts, or techniques contained in the Feedback, and you have no right to compel such use, display, reproduction, or distribution. To the extent the foregoing assignment of rights, title and interest in and to your Feedback is prohibited by applicable law, you hereby grant Conair and any other Licensee a non-exclusive, perpetual, irrevocable, royalty-free, fully paid-up, worldwide license (including the right to sublicense through multiple tiers) to fully use, practice and exploit those non-assignable rights, title and interest, including, but not limited to, the right to use, reproduce, adapt, publicly perform, publicly display, modify, prepare derivative works, publish, transmit and distribute your Feedback, or any portion thereof, in any form, medium or distribution method now known or hereafter existing, known or developed, for any purpose, and to develop, manufacture, have manufactured, license, market, and sell, directly or indirectly, products and services using such Feedback.
              </li>
              <li className="PrivacyTitle">  GENERAL</li>
              <li>Tasha prefers to advise you if we feel you are not complying with these Terms and to recommend any necessary corrective action. However, certain violations of these Terms, as determined by Tasha, may result in immediate termination of your access to the Sites or ability to use our Mobile Applications without prior notice to you. The Federal Arbitration Act, Connecticut state law and applicable U.S. federal law, without regard to the choice or conflicts of law provisions, will govern these Terms. Foreign laws do not apply. The United Nations on Contracts for the International Sale of Goods and any laws based on the Uniform Computer Information Transactions Act (UCITA) shall not apply to this Agreement. Except for Disputes subject to arbitration as described above, any disputes relating to these Terms, the Sites, the Mobile Applications or the Services will be heard in the courts located in Fairfield County in the State of Connecticut. If any of these Terms is found to be inconsistent with applicable law, then such term shall be interpreted to reflect the intentions of the parties, and no other terms will be modified. Tasha’s failure to enforce any of these Terms is not a waiver of such term. These Terms are the entire agreement between you and Tasha and supersede all prior or contemporaneous negotiations, discussions or agreements between you and Tasha about the Sites, the Mobile Applications, and/or any Services. The proprietary rights, disclaimer of warranties, representations made by you, indemnities, limitations of liability and general provisions shall survive any termination of these Terms.</li>
                
                
                
                </li>
            
            
            </ul>

        </div>
    );
}
export default Privacy;